# Generated by Django 5.0.6 on 2024-05-30 06:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingapp', '0004_assignment_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermember',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usermember', to=settings.AUTH_USER_MODEL),
        ),
    ]
