# Generated by Django 5.0.6 on 2024-05-31 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainingapp', '0007_attendance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='user_member',
            new_name='user_members',
        ),
    ]
