# Generated by Django 5.0.6 on 2024-06-01 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingapp', '0010_leaverequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermember',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
