# Generated by Django 5.0.6 on 2024-06-01 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingapp', '0011_usermember_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
