# Generated by Django 5.0.6 on 2024-06-01 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingapp', '0012_assignment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
